### ISSUE TITLE
not found leetcode-entry.h

### ISSUE THREAD

**Issue by feng1o** [XavierCai1996/vscode-leetcode-cpp-debug#25]
> ,,leetcode-main.cpp:5:28: fatal error: leetcode-entry.h: No such file or directory

**Comment by feng1o** [comment]
how to get this header ? tks

**Comment by feng1o** [comment]
i copy leetcode-entry.h from your repository, and then errors:

```
leetcode-entry.h:9:31: fatal error: leetcode-handler.h: No such file or directory
  #include "leetcode-handler.h"
```

**Comment by xavier-cai** [comment]
Hi, sorry for the late response.

The stub files will be put into the same directory as your code file:

```
stubFileHelper.install(path.dirname(solutionEditor.document.uri.fsPath))
```
[https://github.com/xavier-cai/vscode-leetcode-cpp-debug/blob/master/src/leetCodeDebugger.ts#L101](url)

So the issue may be because your C++ debugger does not recognize the header correctly, for example:
```
1. your code file is located in /X/Y/A.cpp
2. then the stub files will be put into /X/Y/ like /X/Y/leetcode-entry.h
3. and stub code will be like #include "leetcode-entry.h" but the C++ debugger doesn't recognize the path /X/Y/ as a valid header path
```

To dive deep the issue, here is the suggestion:
1. Change the Extension Settings “Delete Temporary Contents” to false and find where are the stub files
2. Try to know how/where your C++ debugger finds a header file
